// <auto-generated />
namespace LabCodeFirst.Migrations.Locations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addforeignkey3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addforeignkey3));
        
        string IMigrationMetadata.Id
        {
            get { return "201710061031026_addforeignkey3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
